# ██╗░░░██╗███████╗██████╗░░██████╗██╗░█████╗░███╗░░██╗██████╗░██╗░░░░░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
# ██║░░░██║██╔════╝██╔══██╗██╔════╝██║██╔══██╗████╗░██║██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
# ╚██╗░██╔╝█████╗░░██████╔╝╚█████╗░██║██║░░██║██╔██╗██║██████╦╝██║░░░░░██║░░██║██║░░╚═╝█████═╝░█████╗░░██║░░██║
# ░╚████╔╝░██╔══╝░░██╔══██╗░╚═══██╗██║██║░░██║██║╚████║██╔══██╗██║░░░░░██║░░██║██║░░██╗██╔═██╗░██╔══╝░░██║░░██║
# ░░╚██╔╝░░███████╗██║░░██║██████╔╝██║╚█████╔╝██║░╚███║██████╦╝███████╗╚█████╔╝╚█████╔╝██║░╚██╗███████╗██████╔╝
# ░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═════╝░╚═╝░╚════╝░╚═╝░░╚══╝╚═════╝░╚══════╝░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═════╝░

# Socials / Ссылки:
# • Contact with me / Связаться: https://t.me/ilezovofficial
# • Telegram Channel / Телеграм канал: https://t.me/fastlimbo
# • GitHub: https://github.com/ilezzov-code

# By me coffee / Поддержать разработчика:
# • YooMoney: https://yoomoney.ru/to/4100118180919675
# • Telegram Gift: https://t.me/ilezovofficial
# • TON: UQCInXoHOJAlMpZ-8GIHqv1k0dg2E4pglKAIxOf3ia5xHmKV
# • BTC: 1KCM1QN9TNYRevvQD63UF81oBRSK67vCon
# • Card: 2200 7007 3348 7101 (T-Bank)

# Check for updates / Проверять наличие обновлений
check-updates: true

# Версии протокола
# Версия Minecraft | Номер протокола
# 1.7.2-1.7.3-1.7.4-1.7.5 | 4
# 1.7.6-1.7.7-1.7.8-1.7.9-1.7.10 | 5
# 1.8-1.8.1-1.8.2-1.8.3-1.8.4-1.8.5-1.8.6-1.8.7-1.8.8-1.8.9 | 47
# 1.9 | 107
# 1.9.1,108
# 1.9.2 | 109
# 1.9.3-1.9.4 | 110
# 1.10-1.10.1-1.10.2 | 210
# 1.11 | 315
# 1.11.1-1.11.2 | 316
# 1.12 | 335
# 1.12.1 | 338
# 1.12.2 | 340
# 1.13 | 393
# 1.13.1 | 401
# 1.13.2 | 404
# 1.14 | 477
# 1.14.1 | 480
# 1.14.2 | 485
# 1.14.3 | 490
# 1.14.4 | 498
# 1.15 | 573
# 1.15.1 | 575
# 1.15.2 | 578
# 1.16 | 735
# 1.16.1 | 736
# 1.16.2 | 751
# 1.16.3 | 753
# 1.16.4-1.16.5 | 754
# 1.17 | 755
# 1.17.1 | 756
# 1.18-1.18.1 | 757
# 1.18.2 | 758
# 1.19 | 759
# 1.19.1-1.19.2 | 760
# 1.19.3 | 761
# 1.19.4 | 762
# 1.20-1.20.1 | 763
# 1.20.2 | 764
# 1.20.3-1.20.4 | 765
# 1.20.5-1.20.6 | 766
# 1.21-1.21.1 | 767
# 1.21.2-1.21.3 | 768
# 1.21.4 | 769
# 1.21.5 | 770
# 1.21.6 | 771
# 1.21.7-1.21.8 | 772
# 1.21.9-1.21.10 | 773
# 1.21.11 | 774

# Настройки фильтрации версий
version-filter:
  # Минимальная версия протокола, с которой можно подключиться к серверу
  min-version-protocol: 4
  # Используйте -1, если не хотите ставить ограничение на последнюю версию игры
  max-version-protocol: -1
  # Заблокированные версии
  blocked-protocols:
    - 355
    - 393
  # Отключить игроков с неподдерживаемой версией после /versblock reload
  kick-connected: true


# Сообщения для игроков при кике (поддерживает MiniMessage)
messages:
  main-command: "<gradient:#FF7272:#FFC976>MineCoal</gradient> <dark_gray>| <white>Команды плагина:\n\n<yellow>/versionblocked reload <white>— перезагрузить конфигурацию"
  main-command-reload: "<gradient:#FF7272:#FFC976>MineCoal</gradient> <dark_gray>| <white>Конфигурация перезагружена"
  main-command-reload-error: "<gradient:#FF7272:#FFC976>MineCoal</gradient> <dark_gray>| <white>Не удалось перезагрузить конфигурацию"
  main-command-permission-error: "<gradient:#FF7272:#FFC976>MineCoal</gradient> <dark_gray>| <white>У вас нет прав для выполнения этой команды"

  kick-reason: |
    <b><gradient:#FF7272:#FFC976>MineCoal</gradient></b>
    
    <#F0EDFF>Вы используете неподдерживаемую версию игры. Обновите ваш клиент до <yellow>1.21-1.21.x
    
    <#F0EDFF>Проблема не решена или есть вопрос? — Напиши нам 
    <gradient:#10DFFC:#00F6CE>ᴠᴋ: @minecoals</gradient> <#F0EDFF>| <gradient:#10FCE9:#00F6CE>ᴛɢ: @minecoalrobot</gradient>

  checked-players: "<gradient:#FF7272:#FFC976>MineCoal</gradient> <dark_gray>| <white>Проверено игроков: <yellow>{checked_players}<white>, из них кикнуто: <yellow>{kicked_players}"

# Логирование в консоль
logging:
  enabled: true
  format: "Игрок {player} пытался зайти с версии {protocol}  ({minecraft_version})"

# Internal configuration version. Do not modify!
# Внутренняя версия конфигурации. Не редактируйте!
config-version: ${project.version}