# ███████╗░█████╗░░██████╗████████╗██╗░░░░░██╗███╗░░░███╗██████╗░░█████╗░
# ██╔════╝██╔══██╗██╔════╝╚══██╔══╝██║░░░░░██║████╗░████║██╔══██╗██╔══██╗
# █████╗░░███████║╚█████╗░░░░██║░░░██║░░░░░██║██╔████╔██║██████╦╝██║░░██║
# ██╔══╝░░██╔══██║░╚═══██╗░░░██║░░░██║░░░░░██║██║╚██╔╝██║██╔══██╗██║░░██║
# ██║░░░░░██║░░██║██████╔╝░░░██║░░░███████╗██║██║░╚═╝░██║██████╦╝╚█████╔╝
# ╚═╝░░░░░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝╚═╝░░░░░╚═╝╚═════╝░░╚════╝░

# Socials / Ссылки:
# • Contact with me / Связаться: https://t.me/ilezovofficial
# • Telegram Channel / Телеграм канал: https://t.me/fastlimbo
# • GitHub: https://github.com/ilezzov-code

# By me coffee / Поддержать разработчика:
# • YooMoney: https://yoomoney.ru/to/4100118180919675
# • Telegram Gift: https://t.me/ilezovofficial
# • TON: UQCInXoHOJAlMpZ-8GIHqv1k0dg2E4pglKAIxOf3ia5xHmKV
# • BTC: 1KCM1QN9TNYRevvQD63UF81oBRSK67vCon
# • Card: 2200 7007 3348 7101 (T-Bank)

# Check for updates / Проверять наличие обновлений
check-updates: true



# Internal configuration version. Do not modify!
# Внутренняя версия конфигурации. Не редактируйте!
config-version: ${project.version}